{
 "title": "Minio: dashboard",
 "description": "minio dashboard",
 "tags": [ "minio" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(minio_disks_total,instance)"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "Minio is a high performance distributed object storage server, designed for large-scale private cloud infrastructure. For more information, check out the docs.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "content": "<img src=\"https://www.dropbox.com/s/s5z6rn7offp7ov3/Minio_Logo_White.png?raw=1\" style=\"height: 55px;\"></img>\n<img src=\"https://www.dropbox.com/s/59wm2aemin3cvsc/Minio_wm_light_32px.png?raw=1\" style=\"height: 40px;\"></img>\n<p style=\"margin-top: 10px;\"><small>\nMinio is a high performance distributed object storage server, designed for \nlarge-scale private cloud infrastructure. For more information, check out the <a href=\"https://docs.minio.io\">docs</a>.\n</small></p>"
  },
  {
   "title": "Cluster size",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(minio_disks_total{instance=~\"$instance\"}) by(instance)"
    }
   ]
  },
  {
   "title": "Ready",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(minio_disks_offline{instance=~\"$instance\"}) by(instance)/sum(minio_disks_total{instance=~\"$instance\"}) by(instance)*100"
    }
   ]
  },
  {
   "title": "Data Transmited",
   "type": "graph",
   "description": "Data sent by current Minio server instance",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(s3_tx_bytes_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "Transmited:"
    }
   ]
  },
  {
   "title": "Data Received",
   "type": "graph",
   "description": "Data received by current Minio server instance",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(s3_rx_bytes_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "Received:"
    }
   ]
  },
  {
   "title": "Total In/Out Throughput",
   "type": "graph",
   "description": "Data received x transmited by current Minio server instance",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(s3_rx_bytes_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "Received: "
    },
    {
     "expr": "rate(s3_tx_bytes_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "Transmited:"
    }
   ]
  },
  {
   "title": "HTTP Requests duration/s",
   "type": "graph",
   "description": "The current aggregate time spent servicing all HTTP requests  in seconds",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(s3_ttfb_seconds_sum{api=\"getobject\",instance=~\"$instance\"}[5m])",
     "legendFormat": "getobject"
    },
    {
     "expr": "rate(s3_ttfb_seconds_sum{api=\"listobjectsv1\",instance=~\"$instance\"}[5m])",
     "legendFormat": "listobjectsv1"
    },
    {
     "expr": "rate(s3_ttfb_seconds_sum{api=\"listobjectsv2\",instance=~\"$instance\"}[5m])",
     "legendFormat": "PUT"
    }
   ]
  },
  {
   "title": "Disks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(minio_disks_total{instance=~\"$instance\"}) by(instance)",
     "legendFormat": "Total disks"
    },
    {
     "expr": "sum(minio_disks_offline{instance=~\"$instance\"}) by(instance)",
     "legendFormat": "Offline disks"
    }
   ]
  }
 ]
}